on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please-uat

jobs:
  release-please-prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: prerelease
        with:
          config-file: release-please-config-prerelease.json
          manifest-file: .release-please-manifest.json
      - uses: google-github-actions/release-please-action@v4
        id: prod
        if: ${{ steps.prerelease.outputs.release_created }}
        with:
          config-file: release-please-config-prod.json
          manifest-file: .release-please-manifest.json