on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please-uat

jobs:
  release-please-prerelease:
    runs-on: ubuntu-latest
    outputs:
      prs_created: ${{ steps.prerelease.outputs.prs_created }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: prerelease
        with:
          config-file: release-please-config-prerelease.json
          manifest-file: .release-please-manifest.json

  release-please-prod:
    runs-on: ubuntu-latest
    needs: release-please-prerelease
    if: ${{ needs.release-please-prerelease.outputs.prs_created == 'true' }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: prod
        with:
          config-file: release-please-config-prod.json
          manifest-file: .release-please-manifest.json